### ISSUE TITLE
Chaining CodeSets updates 210127

### ISSUE THREAD

**Issue by ltindale** [TalhoukLab/OV_Histotypes#29]
Final examples for CS chaining paper:
2-step normalization. Normalize CS5 -->4 using SetB Pools, then further normalizing those results to CS3 using SetA Pools as if they were originally run in CS4. Demonstrating that CS5 is now normalized to CS3.

**PART 1**

- [x] Create table of histotype distribution for the 45 samples common to CS3/4/5
- [x] Create table showing how many of each reference Pool are in each CodeSet

**SetA = Pools 1-3
SetB = Pools 9-11 (new stocks equivalent to Pools 1-3)
SetC = Pools 4-8 (cell-line samples)**

**PART 2**

- [x] Normalize CS5 to CS4 using SetB Pools
- CS4 expression held fixed
- X5B(normB) = X5B - R5B +R4B

- [x] Normalize CS5normB to CS3 using SetA Pools as if originally run in CS4
- CS3 expression held fixed
- X5A(normA) = X5B(normB) - R4A + R3A

- [x] Normalize CS4 to CS3 using SetA Pools
- CS3 expression held fixed
- X4A(normA) = X4A - R4A + R3A

Create histogram figures:
- [x] CS5 CodeSet Chaining Concordance Measure Distributions: Row1 - CS5 vs CS3; Row2 - CS5normB vs CS3; Row3 - CS5normA vs CS3
- [x] CS4 Concordance Measure Distributions: Row1 - CS4 vs CS3; Row2 - CS4normA vs CS3
- [x] CS4 and CS5 Concordance Measure Distributions: Row1 - CS5 vs CS4; Row2 - CS5normB vs CS4

**PART 3**
Repeat Part 2 using SetC Pools instead of SetB Pools

- [x] Normalize CS5 to CS4 using SetC Pools
- CS4 expression held fixed
- X5C(normC) = X5C - R5C +R4C

- [x] Normalize CS5normC to CS3 using SetA Pools as if originally run in CS4
- CS3 expression held fixed
- X5C(normA) = X5C(normC) - R4A + R3A

- [x] Normalize CS4 to CS3 using SetA Pools
- CS3 expression held fixed
- X4A(normA) = X4A - R4A + R3A

Create histogram figures:
- [x] CS5 CodeSet Chaining Concordance Measure Distributions: Row1 - CS5 vs CS3; Row2 - CS5normC vs CS3; Row3 - CS5normA vs CS3
- [x] CS4 Concordance Measure Distributions: Row1 - CS4 vs CS3; Row2 - CS4normA vs CS3
- [x] CS4 and CS5 Concordance Measure Distributions: Row1 - CS5 vs CS4; Row2 - CS5normC vs CS4
